In [11]:
import re

In [1]:
result = {'backend': {'name': 'simulator'},
 'calibration': {},
 'creationDate': '2017-11-04T21:51:16.880Z',
 'deleted': False,
 'id': 'c2c7c6e0341b389234b4004a44ec7921',
 'maxCredits': 3,
 'qasms': [{'data': {'additionalData': {'seed': 3726169778},
    'counts': {'00100': 1000},
    'creg_labels': 'ans[5]',
    'date': '2017-11-04T21:51:17.564Z',
    'time': 0.278681},
   'executionId': '8730a4967efc254e25e5f62cf83bb483',
   'qasm': '// draper(0b10,0b00)->00100\n\ninclude "qelib1.inc";\nqreg q[5];\ncreg ans[5];\nu2(0.0,3.141592653589793) q[4];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu2(0.0,3.141592653589793) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.0) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.0) q[2];\nu2(0.0,3.141592653589793) q[2];\ncx q[2],q[4];\nu2(0.0,3.141592653589793) q[4];\nu2(0.0,3.141592653589793) q[4];\nu2(0.0,3.141592653589793) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.392699081698724) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.392699081698724) q[2];\nu3(-0.392699081698724,0.0,0.0) q[2];\nu2(0.0,3.141592653589793) q[2];\ncx q[2],q[4];\nu2(0.0,3.141592653589793) q[4];\nu1(0.785398163397448) q[4];\nu2(0.0,3.141592653589793) q[4];\nu3(3.141592653589793,0.0,3.141592653589793) q[4];\nu1(-0.0) q[4];\nu3(3.141592653589793,0.0,3.141592653589793) q[4];\nu1(0.0) q[4];\ncx q[3],q[4];\nu3(3.141592653589793,0.0,3.141592653589793) q[4];\nu1(0.785398163397448) q[4];\nu3(3.141592653589793,0.0,3.141592653589793) q[4];\nu1(-0.785398163397448) q[4];\nu3(-0.785398163397448,0.0,0.0) q[4];\ncx q[3],q[4];\nu3(0.785398163397448,0.0,0.0) q[4];\nu3(3.141592653589793,0.0,3.141592653589793) q[4];\nu1(-0.785398163397448) q[4];\nu3(3.141592653589793,0.0,3.141592653589793) q[4];\nu1(0.785398163397448) q[4];\nu2(0.0,3.141592653589793) q[4];\nu2(0.0,3.141592653589793) q[4];\nu1(1.570796326794897) q[3];\nu2(0.0,3.141592653589793) q[2];\nu3(0.392699081698724,0.0,0.0) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.392699081698724) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.392699081698724) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.0) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.0) q[2];\ncx q[3],q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.392699081698724) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.392699081698724) q[2];\nu3(-0.392699081698724,0.0,0.0) q[2];\ncx q[3],q[2];\nu3(0.392699081698724,0.0,0.0) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.392699081698724) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.392699081698724) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.0) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.0) q[2];\nu2(0.0,3.141592653589793) q[2];\nu1(0.785398163397448) q[3];\nu2(0.0,3.141592653589793) q[0];\ncx q[2],q[0];\nu2(0.0,3.141592653589793) q[0];\nu2(0.0,3.141592653589793) q[0];\nu2(0.0,3.141592653589793) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.785398163397448) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.785398163397448) q[2];\nu3(-0.785398163397448,0.0,0.0) q[2];\nu2(0.0,3.141592653589793) q[2];\ncx q[2],q[0];\nu2(0.0,3.141592653589793) q[0];\nu1(1.570796326794897) q[0];\nu2(0.0,3.141592653589793) q[2];\nu3(0.785398163397448,0.0,0.0) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.785398163397448) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.785398163397448) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.0) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.0) q[2];\nu2(0.0,3.141592653589793) q[2];\ncx q[2],q[4];\nu2(0.0,3.141592653589793) q[4];\nu2(0.0,3.141592653589793) q[4];\nu2(0.0,3.141592653589793) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.392699081698724) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.392699081698724) q[2];\nu3(0.392699081698724,0.0,0.0) q[2];\nu2(0.0,3.141592653589793) q[2];\ncx q[2],q[4];\nu2(0.0,3.141592653589793) q[4];\nu1(-0.785398163397448) q[4];\nu2(0.0,3.141592653589793) q[2];\nu3(-0.392699081698724,0.0,0.0) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.392699081698724) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.392699081698724) q[2];\nu2(0.0,3.141592653589793) q[2];\n\nmeasure q[3] -> ans[3];\nmeasure q[1] -> ans[1];\nmeasure q[0] -> ans[0];\nmeasure q[4] -> ans[4];\nmeasure q[2] -> ans[2];',
   'status': 'DONE'}],
 'shots': 1000,
 'status': 'COMPLETED',
 'usedCredits': 0,
 'userId': '3420e4521ca5c81ba1ecf94166d88487'}

In [7]:
qasm = result["qasms"][0]["qasm"].split("\n")

In [9]:
len(qasm)

125

In [15]:
bla = list(filter(lambda x: re.sub(r"u1\(-?0.0\).*;", "", x), qasm))
print(len(bla))
bla

113


['// draper(0b10,0b00)->00100',
 'include "qelib1.inc";',
 'qreg q[5];',
 'creg ans[5];',
 'u2(0.0,3.141592653589793) q[4];',
 'u3(3.141592653589793,0.0,3.141592653589793) q[2];',
 'u2(0.0,3.141592653589793) q[2];',
 'u3(3.141592653589793,0.0,3.141592653589793) q[2];',
 'u3(3.141592653589793,0.0,3.141592653589793) q[2];',
 'u2(0.0,3.141592653589793) q[2];',
 'cx q[2],q[4];',
 'u2(0.0,3.141592653589793) q[4];',
 'u2(0.0,3.141592653589793) q[4];',
 'u2(0.0,3.141592653589793) q[2];',
 'u3(3.141592653589793,0.0,3.141592653589793) q[2];',
 'u1(0.392699081698724) q[2];',
 'u3(3.141592653589793,0.0,3.141592653589793) q[2];',
 'u1(-0.392699081698724) q[2];',
 'u3(-0.392699081698724,0.0,0.0) q[2];',
 'u2(0.0,3.141592653589793) q[2];',
 'cx q[2],q[4];',
 'u2(0.0,3.141592653589793) q[4];',
 'u1(0.785398163397448) q[4];',
 'u2(0.0,3.141592653589793) q[4];',
 'u3(3.141592653589793,0.0,3.141592653589793) q[4];',
 'u3(3.141592653589793,0.0,3.141592653589793) q[4];',
 'cx q[3],q[4];',
 'u3(3.141592653

In [2]:
from algorithms import draper
from matplotlib import pyplot
import numpy as np
from qiskit import QuantumProgram, QuantumRegister, QuantumCircuit, Result

In [4]:
token = "a6c65f024279c033c9368bd14e6f9079b71fdfd00625b1f3d3573475c97d84d429c8b4316aa572709dd2670e9a069e735f127342360a7ec6bd8f17f82a997ba2"
url = 'https://quantumexperience.ng.bluemix.net/api'

Q_program: QuantumProgram = QuantumProgram()
Q_program.set_api(token, url)

qasm, expected = draper.create_experiment(Q_program, "0b10", "0b00" ,"draper", 
                                          "local_qasm_simulator", draper.algorithm_test)

Job: 0b10 + 0b00 = 0b10. Expecting answer: 00100
a1 setting to 1


In [6]:
qasm.split("\n")

['// draper(0b10,0b00)->00100',
 'OPENQASM 2.0;',
 'include "qelib1.inc";',
 'qreg q[5];',
 'creg ans[5];',
 'u3(3.141592653589793,0.0,3.141592653589793) q[4];',
 'u1(-0.0) q[4];',
 'u3(3.141592653589793,0.0,3.141592653589793) q[4];',
 'u1(0.0) q[4];',
 'cx q[3],q[4];',
 'u3(3.141592653589793,0.0,3.141592653589793) q[4];',
 'u1(0.785398163397448) q[4];',
 'u3(3.141592653589793,0.0,3.141592653589793) q[4];',
 'u1(-0.785398163397448) q[4];',
 'u3(-0.785398163397448,0.0,0.0) q[4];',
 'cx q[3],q[4];',
 'u3(0.785398163397448,0.0,0.0) q[4];',
 'u3(3.141592653589793,0.0,3.141592653589793) q[4];',
 'u1(-0.785398163397448) q[4];',
 'u3(3.141592653589793,0.0,3.141592653589793) q[4];',
 'u1(0.785398163397448) q[4];',
 'u1(1.570796326794897) q[3];',
 'u3(3.141592653589793,0.0,3.141592653589793) q[2];',
 '',
 'measure q[4] -> ans[4];',
 'measure q[3] -> ans[3];',
 'measure q[2] -> ans[2];',
 'measure q[1] -> ans[1];',
 'measure q[0] -> ans[0];']

In [9]:
import numpy as np

In [6]:
def u1(lam):
    return np.matrix([[1,0],[0,np.exp(1j*lam)]])

def u2(phi, lam):
    return np.matrix(
        [
            [1/np.sqrt(2),-np.exp(1j*lam)*1/np.sqrt(2)],
            [np.exp(1j*phi)*1/np.sqrt(2),np.exp(1j*lam+1j*phi)*1/np.sqrt(2)]
        ])

def u3(theta,phi,lam):
    return np.matrix([
        [np.cos(theta/2),-np.exp(1j*lam) * np.sin(theta/2)],
        [np.exp(1j*phi) * np.sin(theta/2),np.exp(1j*lam+1j*phi)*np.cos(theta/2)]
    ])

def roundFloat(matrix: np.ndarray):
    return matrix.round(matrix, 2)

In [10]:
np.pi/4

0.7853981633974483

In [9]:
(u3(np.pi,np.pi/8,np.pi)*u3(np.pi,-np.pi/8,np.pi)*u3(-np.pi/8,0.0,0.0)).round(6)

matrix([[ 0.906127-0.37533j ,  0.180240-0.074658j],
        [-0.180240-0.074658j,  0.906127+0.37533j ]])

In [74]:
u3(np.pi,0.0,0.0).round(6)

matrix([[ 0.+0.j, -1.-0.j],
        [ 1.+0.j,  0.+0.j]])

In [42]:
u1(np.pi/4)*u1(np.pi/2)

array([[ 1.00000000+0.j        ,  0.00000000+0.j        ],
       [ 0.00000000+0.j        , -0.70710678+0.70710678j]])

In [43]:
u1(np.pi/4+ np.pi/2)

array([[ 1.00000000+0.j        ,  0.00000000+0.j        ],
       [ 0.00000000+0.j        , -0.70710678+0.70710678j]])