In [11]:
import re

In [1]:
result = {'backend': {'name': 'simulator'},
 'calibration': {},
 'creationDate': '2017-11-04T21:51:16.880Z',
 'deleted': False,
 'id': 'c2c7c6e0341b389234b4004a44ec7921',
 'maxCredits': 3,
 'qasms': [{'data': {'additionalData': {'seed': 3726169778},
    'counts': {'00100': 1000},
    'creg_labels': 'ans[5]',
    'date': '2017-11-04T21:51:17.564Z',
    'time': 0.278681},
   'executionId': '8730a4967efc254e25e5f62cf83bb483',
   'qasm': '// draper(0b10,0b00)->00100\n\ninclude "qelib1.inc";\nqreg q[5];\ncreg ans[5];\nu2(0.0,3.141592653589793) q[4];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu2(0.0,3.141592653589793) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.0) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.0) q[2];\nu2(0.0,3.141592653589793) q[2];\ncx q[2],q[4];\nu2(0.0,3.141592653589793) q[4];\nu2(0.0,3.141592653589793) q[4];\nu2(0.0,3.141592653589793) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.392699081698724) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.392699081698724) q[2];\nu3(-0.392699081698724,0.0,0.0) q[2];\nu2(0.0,3.141592653589793) q[2];\ncx q[2],q[4];\nu2(0.0,3.141592653589793) q[4];\nu1(0.785398163397448) q[4];\nu2(0.0,3.141592653589793) q[4];\nu3(3.141592653589793,0.0,3.141592653589793) q[4];\nu1(-0.0) q[4];\nu3(3.141592653589793,0.0,3.141592653589793) q[4];\nu1(0.0) q[4];\ncx q[3],q[4];\nu3(3.141592653589793,0.0,3.141592653589793) q[4];\nu1(0.785398163397448) q[4];\nu3(3.141592653589793,0.0,3.141592653589793) q[4];\nu1(-0.785398163397448) q[4];\nu3(-0.785398163397448,0.0,0.0) q[4];\ncx q[3],q[4];\nu3(0.785398163397448,0.0,0.0) q[4];\nu3(3.141592653589793,0.0,3.141592653589793) q[4];\nu1(-0.785398163397448) q[4];\nu3(3.141592653589793,0.0,3.141592653589793) q[4];\nu1(0.785398163397448) q[4];\nu2(0.0,3.141592653589793) q[4];\nu2(0.0,3.141592653589793) q[4];\nu1(1.570796326794897) q[3];\nu2(0.0,3.141592653589793) q[2];\nu3(0.392699081698724,0.0,0.0) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.392699081698724) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.392699081698724) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.0) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.0) q[2];\ncx q[3],q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.392699081698724) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.392699081698724) q[2];\nu3(-0.392699081698724,0.0,0.0) q[2];\ncx q[3],q[2];\nu3(0.392699081698724,0.0,0.0) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.392699081698724) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.392699081698724) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.0) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.0) q[2];\nu2(0.0,3.141592653589793) q[2];\nu1(0.785398163397448) q[3];\nu2(0.0,3.141592653589793) q[0];\ncx q[2],q[0];\nu2(0.0,3.141592653589793) q[0];\nu2(0.0,3.141592653589793) q[0];\nu2(0.0,3.141592653589793) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.785398163397448) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.785398163397448) q[2];\nu3(-0.785398163397448,0.0,0.0) q[2];\nu2(0.0,3.141592653589793) q[2];\ncx q[2],q[0];\nu2(0.0,3.141592653589793) q[0];\nu1(1.570796326794897) q[0];\nu2(0.0,3.141592653589793) q[2];\nu3(0.785398163397448,0.0,0.0) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.785398163397448) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.785398163397448) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.0) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.0) q[2];\nu2(0.0,3.141592653589793) q[2];\ncx q[2],q[4];\nu2(0.0,3.141592653589793) q[4];\nu2(0.0,3.141592653589793) q[4];\nu2(0.0,3.141592653589793) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.392699081698724) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.392699081698724) q[2];\nu3(0.392699081698724,0.0,0.0) q[2];\nu2(0.0,3.141592653589793) q[2];\ncx q[2],q[4];\nu2(0.0,3.141592653589793) q[4];\nu1(-0.785398163397448) q[4];\nu2(0.0,3.141592653589793) q[2];\nu3(-0.392699081698724,0.0,0.0) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.392699081698724) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.392699081698724) q[2];\nu2(0.0,3.141592653589793) q[2];\n\nmeasure q[3] -> ans[3];\nmeasure q[1] -> ans[1];\nmeasure q[0] -> ans[0];\nmeasure q[4] -> ans[4];\nmeasure q[2] -> ans[2];',
   'status': 'DONE'}],
 'shots': 1000,
 'status': 'COMPLETED',
 'usedCredits': 0,
 'userId': '3420e4521ca5c81ba1ecf94166d88487'}

In [7]:
qasm = result["qasms"][0]["qasm"].split("\n")

In [9]:
len(qasm)

125

In [15]:
bla = list(filter(lambda x: re.sub(r"u1\(-?0.0\).*;", "", x), qasm))
print(len(bla))
bla

113


['// draper(0b10,0b00)->00100',
 'include "qelib1.inc";',
 'qreg q[5];',
 'creg ans[5];',
 'u2(0.0,3.141592653589793) q[4];',
 'u3(3.141592653589793,0.0,3.141592653589793) q[2];',
 'u2(0.0,3.141592653589793) q[2];',
 'u3(3.141592653589793,0.0,3.141592653589793) q[2];',
 'u3(3.141592653589793,0.0,3.141592653589793) q[2];',
 'u2(0.0,3.141592653589793) q[2];',
 'cx q[2],q[4];',
 'u2(0.0,3.141592653589793) q[4];',
 'u2(0.0,3.141592653589793) q[4];',
 'u2(0.0,3.141592653589793) q[2];',
 'u3(3.141592653589793,0.0,3.141592653589793) q[2];',
 'u1(0.392699081698724) q[2];',
 'u3(3.141592653589793,0.0,3.141592653589793) q[2];',
 'u1(-0.392699081698724) q[2];',
 'u3(-0.392699081698724,0.0,0.0) q[2];',
 'u2(0.0,3.141592653589793) q[2];',
 'cx q[2],q[4];',
 'u2(0.0,3.141592653589793) q[4];',
 'u1(0.785398163397448) q[4];',
 'u2(0.0,3.141592653589793) q[4];',
 'u3(3.141592653589793,0.0,3.141592653589793) q[4];',
 'u3(3.141592653589793,0.0,3.141592653589793) q[4];',
 'cx q[3],q[4];',
 'u3(3.141592653

In [1]:
from algorithms import draper
from matplotlib import pyplot
import numpy as np
from qiskit import QuantumProgram, QuantumRegister, QuantumCircuit, Result

In [2]:
from interfaces import ApiCredentials
import credentials

creds = ApiCredentials()

Q_program: QuantumProgram = QuantumProgram()
Q_program.set_api(creds.GetToken(), creds.GetApiUri())

In [149]:
jobs = Q_program.get_api().get_jobs(limit=100000)

In [150]:
import re

data = filter(lambda x: x["status"] == "COMPLETED",jobs)
data = map(FlattenData, data)
data = filter(lambda x: len(x["target"]) > 0, data)
data = map(MapToMeaning, data)

list(data)

["['2017-11-04T21:29:14.819Z', False, 'ibmqx4', '0b00', '0b00', '00000', 0.125, '10000', 0.32, '2_1__']",
 "['2017-11-04T21:22:34.948Z', True, 'ibmqx4', '0b00', '0b11', '11101', 0.18, '11101', 0.18, '2_1__']",
 "['2017-11-04T21:15:00.305Z', False, 'ibmqx4', '0b01', '0b01', '01100', 0.192, '11100', 0.203, '2_1__']",
 "['2017-11-04T21:13:48.557Z', True, 'simulator', '0b01', '0b01', '01100', 0.977, '01100', 0.977, '2_1__']",
 "['2017-11-04T22:08:27.390Z', True, 'simulator', '0b00', '0b11', '11101', 0.936, '11101', 0.936, '2_1__']",
 "['2017-11-04T21:21:56.238Z', True, 'simulator', '0b00', '0b11', '11101', 0.945, '11101', 0.945, '2_1__']",
 "['2017-11-04T21:08:55.169Z', False, 'ibmqx4', '0b10', '0b00', '00100', 0.224, '10100', 0.225, '2_1__']",
 "['2017-11-04T21:28:58.243Z', True, 'simulator', '0b00', '0b00', '00000', 1.0, '00000', 1.0, '2_1__']",
 "['2017-11-04T21:06:38.645Z', True, 'simulator', '0b10', '0b00', '00100', 1.0, '00100', 1.0, '2_1__']",
 "['2017-11-04T22:05:56.364Z', True, 'i

In [147]:
def MapToMeaning(row):
    date = row["date"]
    backend = row["backend"]
    m = re.search("// draper\\((.+),(.+)\\)->(\\d+)", row["target"])
    a = m.group(1)
    b = m.group(2)
    counts = row["result"]["data"]["counts"]
    shots = row["shots"]
    expected_result = m.group(3)
    computational_result = max(counts.keys(), key=(lambda key: counts[key]))
    hint_result = "2_1__"
    success = computational_result == expected_result
    computational_result_prob = counts[computational_result]/float(shots)
    expected_result_prob = counts[expected_result]/float(shots)
    
    calibration = row["calibration"]
    
    return str([date,success,backend,a,b,expected_result,expected_result_prob,
                computational_result,computational_result_prob,hint_result])

def FlattenData(x):
    return { 
        'date': x["creationDate"], 
        'target':x["qasms"][0]["qasm"].split('\n')[0], 
        'backend':x["backend"]["name"],
        'result':x["qasms"][0]["result"],
        'calibration':x["calibration"],
        'shots': x["shots"]
    }

In [155]:
Q_program.get_api().backend_status()

{'available': False, 'backend': 'ibmqx4', 'busy': False, 'pending_jobs': 8}

In [10]:
np.pi/4

0.7853981633974483

In [9]:
(u3(np.pi,np.pi/8,np.pi)*u3(np.pi,-np.pi/8,np.pi)*u3(-np.pi/8,0.0,0.0)).round(6)

matrix([[ 0.906127-0.37533j ,  0.180240-0.074658j],
        [-0.180240-0.074658j,  0.906127+0.37533j ]])

In [74]:
u3(np.pi,0.0,0.0).round(6)

matrix([[ 0.+0.j, -1.-0.j],
        [ 1.+0.j,  0.+0.j]])

In [42]:
u1(np.pi/4)*u1(np.pi/2)

array([[ 1.00000000+0.j        ,  0.00000000+0.j        ],
       [ 0.00000000+0.j        , -0.70710678+0.70710678j]])

In [43]:
u1(np.pi/4+ np.pi/2)

array([[ 1.00000000+0.j        ,  0.00000000+0.j        ],
       [ 0.00000000+0.j        , -0.70710678+0.70710678j]])