In [11]:
import re

In [1]:
result = {'backend': {'name': 'simulator'},
 'calibration': {},
 'creationDate': '2017-11-04T21:51:16.880Z',
 'deleted': False,
 'id': 'c2c7c6e0341b389234b4004a44ec7921',
 'maxCredits': 3,
 'qasms': [{'data': {'additionalData': {'seed': 3726169778},
    'counts': {'00100': 1000},
    'creg_labels': 'ans[5]',
    'date': '2017-11-04T21:51:17.564Z',
    'time': 0.278681},
   'executionId': '8730a4967efc254e25e5f62cf83bb483',
   'qasm': '// draper(0b10,0b00)->00100\n\ninclude "qelib1.inc";\nqreg q[5];\ncreg ans[5];\nu2(0.0,3.141592653589793) q[4];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu2(0.0,3.141592653589793) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.0) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.0) q[2];\nu2(0.0,3.141592653589793) q[2];\ncx q[2],q[4];\nu2(0.0,3.141592653589793) q[4];\nu2(0.0,3.141592653589793) q[4];\nu2(0.0,3.141592653589793) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.392699081698724) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.392699081698724) q[2];\nu3(-0.392699081698724,0.0,0.0) q[2];\nu2(0.0,3.141592653589793) q[2];\ncx q[2],q[4];\nu2(0.0,3.141592653589793) q[4];\nu1(0.785398163397448) q[4];\nu2(0.0,3.141592653589793) q[4];\nu3(3.141592653589793,0.0,3.141592653589793) q[4];\nu1(-0.0) q[4];\nu3(3.141592653589793,0.0,3.141592653589793) q[4];\nu1(0.0) q[4];\ncx q[3],q[4];\nu3(3.141592653589793,0.0,3.141592653589793) q[4];\nu1(0.785398163397448) q[4];\nu3(3.141592653589793,0.0,3.141592653589793) q[4];\nu1(-0.785398163397448) q[4];\nu3(-0.785398163397448,0.0,0.0) q[4];\ncx q[3],q[4];\nu3(0.785398163397448,0.0,0.0) q[4];\nu3(3.141592653589793,0.0,3.141592653589793) q[4];\nu1(-0.785398163397448) q[4];\nu3(3.141592653589793,0.0,3.141592653589793) q[4];\nu1(0.785398163397448) q[4];\nu2(0.0,3.141592653589793) q[4];\nu2(0.0,3.141592653589793) q[4];\nu1(1.570796326794897) q[3];\nu2(0.0,3.141592653589793) q[2];\nu3(0.392699081698724,0.0,0.0) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.392699081698724) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.392699081698724) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.0) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.0) q[2];\ncx q[3],q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.392699081698724) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.392699081698724) q[2];\nu3(-0.392699081698724,0.0,0.0) q[2];\ncx q[3],q[2];\nu3(0.392699081698724,0.0,0.0) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.392699081698724) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.392699081698724) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.0) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.0) q[2];\nu2(0.0,3.141592653589793) q[2];\nu1(0.785398163397448) q[3];\nu2(0.0,3.141592653589793) q[0];\ncx q[2],q[0];\nu2(0.0,3.141592653589793) q[0];\nu2(0.0,3.141592653589793) q[0];\nu2(0.0,3.141592653589793) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.785398163397448) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.785398163397448) q[2];\nu3(-0.785398163397448,0.0,0.0) q[2];\nu2(0.0,3.141592653589793) q[2];\ncx q[2],q[0];\nu2(0.0,3.141592653589793) q[0];\nu1(1.570796326794897) q[0];\nu2(0.0,3.141592653589793) q[2];\nu3(0.785398163397448,0.0,0.0) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.785398163397448) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.785398163397448) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.0) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.0) q[2];\nu2(0.0,3.141592653589793) q[2];\ncx q[2],q[4];\nu2(0.0,3.141592653589793) q[4];\nu2(0.0,3.141592653589793) q[4];\nu2(0.0,3.141592653589793) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.392699081698724) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.392699081698724) q[2];\nu3(0.392699081698724,0.0,0.0) q[2];\nu2(0.0,3.141592653589793) q[2];\ncx q[2],q[4];\nu2(0.0,3.141592653589793) q[4];\nu1(-0.785398163397448) q[4];\nu2(0.0,3.141592653589793) q[2];\nu3(-0.392699081698724,0.0,0.0) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(0.392699081698724) q[2];\nu3(3.141592653589793,0.0,3.141592653589793) q[2];\nu1(-0.392699081698724) q[2];\nu2(0.0,3.141592653589793) q[2];\n\nmeasure q[3] -> ans[3];\nmeasure q[1] -> ans[1];\nmeasure q[0] -> ans[0];\nmeasure q[4] -> ans[4];\nmeasure q[2] -> ans[2];',
   'status': 'DONE'}],
 'shots': 1000,
 'status': 'COMPLETED',
 'usedCredits': 0,
 'userId': '3420e4521ca5c81ba1ecf94166d88487'}

In [7]:
qasm = result["qasms"][0]["qasm"].split("\n")

In [9]:
len(qasm)

125

In [15]:
bla = list(filter(lambda x: re.sub(r"u1\(-?0.0\).*;", "", x), qasm))
print(len(bla))
bla

113


['// draper(0b10,0b00)->00100',
 'include "qelib1.inc";',
 'qreg q[5];',
 'creg ans[5];',
 'u2(0.0,3.141592653589793) q[4];',
 'u3(3.141592653589793,0.0,3.141592653589793) q[2];',
 'u2(0.0,3.141592653589793) q[2];',
 'u3(3.141592653589793,0.0,3.141592653589793) q[2];',
 'u3(3.141592653589793,0.0,3.141592653589793) q[2];',
 'u2(0.0,3.141592653589793) q[2];',
 'cx q[2],q[4];',
 'u2(0.0,3.141592653589793) q[4];',
 'u2(0.0,3.141592653589793) q[4];',
 'u2(0.0,3.141592653589793) q[2];',
 'u3(3.141592653589793,0.0,3.141592653589793) q[2];',
 'u1(0.392699081698724) q[2];',
 'u3(3.141592653589793,0.0,3.141592653589793) q[2];',
 'u1(-0.392699081698724) q[2];',
 'u3(-0.392699081698724,0.0,0.0) q[2];',
 'u2(0.0,3.141592653589793) q[2];',
 'cx q[2],q[4];',
 'u2(0.0,3.141592653589793) q[4];',
 'u1(0.785398163397448) q[4];',
 'u2(0.0,3.141592653589793) q[4];',
 'u3(3.141592653589793,0.0,3.141592653589793) q[4];',
 'u3(3.141592653589793,0.0,3.141592653589793) q[4];',
 'cx q[3],q[4];',
 'u3(3.141592653

In [1]:
from algorithms import draper
from matplotlib import pyplot
import numpy as np
from qiskit import QuantumProgram, QuantumRegister, QuantumCircuit, Result

In [4]:
token = "5f219a48e77eb29afcb03a42bd6085f3d4d6a9cb4276eb7c8dfdf522f33911eee1f91c3db2f64e542b7fff51299c7d79951238a2fc26cfb1dfa1260b4f561710"
url = 'https://quantumexperience.ng.bluemix.net/api'

Q_program: QuantumProgram = QuantumProgram()
Q_program.set_api(token, url)

In [6]:
jobs = Q_program.get_api().get_jobs(limit=1000)

In [12]:
list(filter(lambda x: x["backend"]["name"] == "ibmqx4",jobs))


[{'backend': {'id': 'c16c5ddebbf8922a7e2a0f5a89cac478', 'name': 'ibmqx4'},
  'calibration': {'fridgeParameters': {'Temperature': {'date': '2017-10-26T11:03:09Z',
     'unit': 'K',
     'value': 0.021},
    'cooldownDate': '2017-09-07'},
   'lastUpdateDate': '2017-10-26T11:03:09.000Z',
   'multiQubitGates': [{'gateError': {'date': '2017-10-26T11:03:09Z',
      'value': 0.01932502536515393},
     'name': 'CX1_0',
     'qubits': [1, 0],
     'type': 'CX'},
    {'gateError': {'date': '2017-10-26T11:03:09Z',
      'value': 0.023044601676600163},
     'name': 'CX2_0',
     'qubits': [2, 0],
     'type': 'CX'},
    {'gateError': {'date': '2017-10-26T11:03:09Z',
      'value': 0.024738466135747345},
     'name': 'CX2_1',
     'qubits': [2, 1],
     'type': 'CX'},
    {'gateError': {'date': '2017-10-26T11:03:09Z',
      'value': 0.035831434121722544},
     'name': 'CX2_4',
     'qubits': [2, 4],
     'type': 'CX'},
    {'gateError': {'date': '2017-10-26T11:03:09Z',
      'value': 0.027181112418

In [6]:
def u1(lam):
    return np.matrix([[1,0],[0,np.exp(1j*lam)]])

def u2(phi, lam):
    return np.matrix(
        [
            [1/np.sqrt(2),-np.exp(1j*lam)*1/np.sqrt(2)],
            [np.exp(1j*phi)*1/np.sqrt(2),np.exp(1j*lam+1j*phi)*1/np.sqrt(2)]
        ])

def u3(theta,phi,lam):
    return np.matrix([
        [np.cos(theta/2),-np.exp(1j*lam) * np.sin(theta/2)],
        [np.exp(1j*phi) * np.sin(theta/2),np.exp(1j*lam+1j*phi)*np.cos(theta/2)]
    ])

def roundFloat(matrix: np.ndarray):
    return matrix.round(matrix, 2)

In [10]:
np.pi/4

0.7853981633974483

In [9]:
(u3(np.pi,np.pi/8,np.pi)*u3(np.pi,-np.pi/8,np.pi)*u3(-np.pi/8,0.0,0.0)).round(6)

matrix([[ 0.906127-0.37533j ,  0.180240-0.074658j],
        [-0.180240-0.074658j,  0.906127+0.37533j ]])

In [74]:
u3(np.pi,0.0,0.0).round(6)

matrix([[ 0.+0.j, -1.-0.j],
        [ 1.+0.j,  0.+0.j]])

In [42]:
u1(np.pi/4)*u1(np.pi/2)

array([[ 1.00000000+0.j        ,  0.00000000+0.j        ],
       [ 0.00000000+0.j        , -0.70710678+0.70710678j]])

In [43]:
u1(np.pi/4+ np.pi/2)

array([[ 1.00000000+0.j        ,  0.00000000+0.j        ],
       [ 0.00000000+0.j        , -0.70710678+0.70710678j]])